name: test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

env:
  SERVICE_DOCKER_IMAGE: backoffice-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Build Docker images
      - name: Build docker image
        run: |
          docker build --tag openmavn/$SERVICE_DOCKER_IMAGE:dev ./
